# Generated by Django 3.1.7 on 2021-03-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
