# Generated by Django 3.1.7 on 2021-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210221_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
