# Generated by Django 3.1.6 on 2021-02-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(default='cw6 0nu', max_length=50, verbose_name='Postcode'),
            preserve_default=False,
        ),
    ]
