# Generated by Django 3.1.6 on 2021-02-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210222_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField()),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('display_name', models.CharField(max_length=100, verbose_name='Display name')),
                ('address_class', models.CharField(max_length=50, verbose_name='Class')),
                ('importance', models.FloatField()),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state_district', models.CharField(max_length=50, verbose_name='State district')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('country_code', models.CharField(max_length=50, verbose_name='Country code')),
            ],
            options={
                'verbose_name': 'AddressLookup',
                'verbose_name_plural': 'AddressLookups',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_class',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='address',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='address',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='address',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state_district',
        ),
        migrations.AddField(
            model_name='address',
            name='num_or_name',
            field=models.CharField(default=-1, max_length=50, verbose_name='House number or name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address_lookup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.addresslookup'),
        ),
    ]
