# Generated by Django 3.1.6 on 2021-03-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20210222_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street_1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_lookup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='addresses.addresslookup'),
            preserve_default=False,
        ),
    ]
