# Generated by Django 3.1.12 on 2021-06-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20210502_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresslookup',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='country_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country code'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='county',
            field=models.CharField(blank=True, max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='importance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='lon',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='place_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='state_district',
            field=models.CharField(blank=True, max_length=50, verbose_name='State district'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='suburb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Suburb'),
        ),
    ]
