# Generated by Django 3.1.12 on 2021-06-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_auto_20210617_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_lookup',
        ),
    ]
