# Generated by Django 3.1.12 on 2021-06-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_auto_20210617_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresslookup',
            name='importance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
