# Generated by Django 3.1.12 on 2021-06-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0011_auto_20210617_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_lookup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='addresses.addresslookup'),
            preserve_default=False,
        ),
    ]
