# Generated by Django 3.1.12 on 2021-07-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0012_address_address_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresslookup',
            name='address_class',
            field=models.CharField(max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='county',
            field=models.CharField(blank=True, max_length=100, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='display_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='state_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='State district'),
        ),
        migrations.AlterField(
            model_name='addresslookup',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, verbose_name='Suburb'),
        ),
    ]
